apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aca
  namespace: default
spec:
  selector:
    matchLabels:
      job: aca
  template:
    metadata:
      labels:
        job: aca
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: er1cthe0ne/aca:aca
        name: aca
        securityContext:
          privileged: true
