= Cloud Fabric Network Agent

== Summary

The Cloud Fabric Network Control Agent runs on each host machine. It serves as a simple stateless proxy between network controller and host machine networking components for control plane operations.


== Requirements

. Network Control Agent will reside on each host machine to interface between network controller and host networking components. The main responsibility is to create and configure network to 
enable connectivity (VPC IP < - > Physical IP mapping) between VMs/Containers within the datacenter and the outside world through EIP.

. It will update networking configuration on the host:
	.. Setup networking/linux bridge/OVS on the host (if not exist)
	.. Create vNIC and vPort for VM/Container (unless this is done by Compute agent) TODO: need to confirm with XiaoNing
	.. Configure vNIC and vPort, connect to the VM/Container
	.. Attach Security group to a vNIC TODO: add more detail
	.. Attached transit agent to the corresponding vNIC(veth) and transit switch/router on the physical NIC
	
. It will also update VPC Configuration (VPC, Subnet, Security Group, Routing) including CRUD (Create/Read/Update/Delete) VPC/Subnet/Endpoint.

== Roles

The network control agent will have the following roles, the code below will live in one binary. 

. Local Host Networking Agent
. Network Agent Health management, transit daemon and agents health 
.. TODO: need to expand this, may live in a seperate doc, post 9/30
. Transit (dataplane) user mode Agent
. Network Component upgrade Agent

== Communication between Network Control Agent and Transit Agent

                    +--------------------+
                    |  Network Control   |
                    |     Agent          |
                    +--------------------+
                    |  Transit Daemon    |
                    +------------------ -+   User Mode
         +--------------------------------------------------+
                    +--------------------+   Kernel Mode
                    |  Transit Agent     |      
                    |     xdp program    |
                    +--------------------+

== Workflow

. Customer Creates a new VPC
	.. Allocate transit router
		... Smart placement [router1, router2]
		... Go to router1, router2 and add VPC to the VPC table (Call “Update VPC”) (VPC table)
. Customer creates new network(subnet)
	.. Allocate transit switch
		... Smart placement [Switch1, Switch2]
		... Go to router1, and router2 and “Update net” (net table)
		... Go to s1, s2, s3 and call “Update net" (net table)
		... Go to s1, s2, s3 and call “Update VPC” (VPC table)
. Customer create a VM with endpoint 1 at net0
	.. Allocate endpoint
		... Go to VM Host create endpoint and update the transit switch info in endpoint table
		... Go to all switches (s1,s2,s3) update endpoint

== Network Configuration

[width="100%",options="header"]
|====================
| VPC table  |
| VPC0 | {10.0.0.0/16,[172.3,172.4]} 
|====================

[width="100%",options="header"]
|====================
|Network Table   |
|Net0   |{10.0.0.0/25,[172.1,172.2]}  
|====================

[width="100%",options="header"]
|====================
|Endpoint Table   |  |  |  
|10.0.0.1  |Net0  |VPC0  |[172.1,...]  
|10.0.0.2    |Net0  |VPC0  |[172.2,...]  
|====================


== Interface with Network Controller
Working in progress...

. API
https://github.com/openstack/neutron/blob/master/neutron/agent/securitygroups_rpc.py

. Protocol 

. Authentication 
Huawei Cloud allow either using tokens (valid for 24 hours) or AK/SK when calling ECS APIs. +
https://support-intl.huaweicloud.com/en-us/api-ecs/en-us_topic_0124306062.html +
Openstack only talks about using authentication token: +
https://docs.openstack.org/ocata/config-reference/common-configurations/auth.html


== Highlevel Components

=== Communication Manager

This will interface with Kafka to process messages from Network Controller. It will subscribe to topics published by Network Controller. Network Control Agent can also publish (health/error) information to Network Controller through Kafka.

=== Network Configurator

1. In order to help Network Controller to determine the host machine network setup. It will collect the network configuration from the host machine and send to Network Controller through Kafka, including:
. SRIOV support
. DPDK support
. Bandwidth (10G/25G/40G)
. IP of the host machine (is it DHCP or assigned?)
2. Network Controller will decide what network configuration to be applied on the host machine, and send it to network control agent through Kafka.
2. It will call OVS daemon to setup and configure OVS
. See OVS solution example in the reference session
3. Connect vNICs to the vPorts on OVS once the VM/Container is running.
. e.g. ovs-vsctl add-port br0 eth0

=== Security policy Manager

Responsible to configure and update the security policies on vNICs/vPorts.

=== Transit Agent Manager

This will interface with user mode Transit daemon to program the transit router/switch/endpoint. Using the below APIs:

                int UPDATE_VPC(rpc_trn_vpc_t) = 1;
                int UPDATE_NET(rpc_trn_network_t) = 2;
                int UPDATE_EP(rpc_trn_endpoint_t) = 3;

                int DELETE_VPC(rpc_trn_vpc_key_t) = 4;
                int DELETE_NET(rpc_trn_network_key_t) = 5;
                int DELETE_EP(rpc_trn_endpoint_key_t) = 6;

                rpc_trn_vpc_t      GET_VPC(rpc_trn_vpc_key_t) = 7;
                rpc_trn_network_t  GET_NET(rpc_trn_network_key_t) = 8;
                rpc_trn_endpoint_t GET_EP(rpc_trn_endpoint_key_t) = 9;

                int LOAD_TRANSIT_XDP(rpc_trn_xdp_intf) = 11;
                int LOAD_TRANSIT_AGENT_XDP(rpc_trn_xdp_intf) = 12;

Note: XDP programs are preloaded on both physical NIC and vNIC as created by the VM. P0 for 9/30.

=== Log Manager

It will create the log file, manage the log configuration and maintain the Network control agent logs. Need to decide on how many days to keep the logs, e.g. 7 days. 

The log should at least contain a timestamp, source file name and line number, message. The network control agent code should be able to specify the log level and can accept the targetted log level through command line.
Syslog is a good target framework, it is a proven mechanism in linux and it is https://askubuntu.com/questions/184949/how-do-i-limit-the-size-of-my-syslog[configurable for our needs]. See reference session for more information.


== API Versioning of Network Control Agent and Network Controller

==== Motivation
When upgrading our codebase, we want to version our components in such a way so that old clients have time to upgrade/adopt, and new clients can use the new features without issues. +
There are multiple strategies that can be used to allow this, and their use cases are project dependent. +

==== Strategy
The current planned strategy is to have clients explicitly state the API version in a config XML/JSON/yaml file. The Network Control Agent will then consume, and execute the correct calls accordingly. +
Further implementation options are compared below ^[2],[3],[4]^

[width="100%",options="header"]
|====================
| Strategy | Pros | Cons 
| Make API self-aware of versions | Maintain only one codebase | Difficult to remove deprecated resources and endpoints 
|   | Deploy just one API codebase  |
| Maintain multiple branches for major API versions | Easy to delete old API versions | Convoluted branch structure deployment pipeline     
|====================

== API Design

. Heart beat with the controller

. CRUD (create/Read/Update/Delete) VPC/Subnet/Endpoint  

. CRUD of Network Security Group and attachment to the Subnet/Endpoint

== Reference

. https://docs.openstack.org/neutron/pike/contributor/internals/openvswitch_agent.html
. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md
. https://dzone.com/articles/backward-compatibility-check-for-rest-apis
. https://stackoverflow.com/questions/29871744/how-do-you-manage-the-underlying-codebase-for-a-versioned-api
. https://stackoverflow.com/questions/29876818/how-can-i-connect-open-vswitch-port-and-virtual-ethernet-interface[OVS solution example]
. https://github.com/futurewei-cloud/Transit/blob/master/docs/modules/ROOT/pages/design/monitoring.adoc[Network Control Agent and SN Agent will work independently]
. https://stackoverflow.com/questions/158457/daemon-logging-in-linux[Logging in Linux]
. https://support.huaweicloud.com/en-us/usermanual-ecs/en-us_topic_0030878383.html[Security Group Rule format in Huawei Cloud]

[width="100%",options="header"]
|====================
| Parameter | Description | Example Value 
| Protocol | Specifies the network protocol for which the security group rule takes effect. The value can be **TCP**, **UDP**, **ICMP**, **HTTP**, or others.
 | TCP 
| Port | Specifies the port or port range for which the security group rule takes effect. The value ranges from **0** to **65535**. | 22 or 22-30 
| Source | Specifies the source for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Inbound**. The value can be an IP address or a security group.
 | 0.0.0.0/0
default
| Destination | Specifies the destination for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Outbound**. The value can be an IP address or a security group. | 0.0.0.0/0
default
|====================
