= Cloud Fabric Alcor Control Agent

== Summary

The Cloud Fabric Alcor Control Agent (ACA) runs on each host machine. It serves as a stateless proxy between network controller and host machine networking components for control plane operations.


== Requirements

. ACA will reside on each host machine to interface between network controller and host networking components. The main responsibility is to configure compute and transit hosts based on message from Alcor Controllers. Which will enable connectivity (VPC IP < - > Physical IP mapping) between VMs/Containers within the datacenter and outside world through EIP for the new Cloud Fabric networking control/data plane.

. It will update networking configuration on the host:
	.. Create vPort for VM/Container (unless this is done by Compute agent)
	.. Configure vNIC and vPort, connect them for the VM/Container
	.. Attach Security group to a vNIC TODO: add more detail after dataplane performance analysis without it
	.. Attached transit agent to the corresponding vNIC(veth) and transit switch/router on the physical NIC

. It will also update VPC Configuration (VPC, Subnet, Security Group, Routing) including CRUD (Create/Read/Update/Delete) VPC/Subnet/Endpoint.

== Roles

ACA will have the following responsibilities, the code will live in one binary.

. Local Host Networking configuration
. ACA Health management, transit daemon and agents health, VM/Container networking health monitoring
.. TODO: need to expand this, will likely live in a seperate doc, post 9/30
. Transit (dataplane) user mode programming proxy
. Network Component upgrade manager

== Communication between ACA and kernel mode Transit Agent

                    +--------------------+
                    |  Alcor Control     |
                    |     Agent          |
                    +--------------------+
                    |  Transit Daemon    |
                    +------------------ -+   User Mode
         +--------------------------------------------------+
                    +--------------------+   Kernel Mode
                    |  Transit Agent     |
                    |     xdp program    |
                    +--------------------+

== Workflow

. Customer creates a new VPC
	.. Allocate transit router
		... Smart placement [router1, router2]
		... Go to router1, router2 and add VPC to the VPC table (Call “Update VPC”) (VPC table)
. Customer creates new network(subnet)
	.. Allocate transit switch
		... Smart placement [Switch1, Switch2]
		... Go to router1, and router2 and “Update net” (net table)
		... Go to s1, s2 and call “Update net" (net table)
. Customer create a VM with endpoint 1 at net0
	.. Allocate endpoint
		... Go to all switches (s1,s2) update endpoint
			.... make sure at least one or more transit switch ready before the next step
			.... TODO: need to be able to notify network controller that a particular transit switch programming is completed
		... Go to VM Host create endpoint and update the transit switch info in endpoint table

== Network Configuration

[width="100%",options="header"]
|====================
| VPC table  |
| VPC0 | {10.0.0.0/16,[172.3,172.4]}
|====================

[width="100%",options="header"]
|====================
|Network Table   |
|Net0   |{10.0.0.0/25,[172.1,172.2]}
|====================

[width="100%",options="header"]
|====================
|Endpoint Table   |  |  |
|10.0.0.1  |Net0  |VPC0  |[172.1,...]
|10.0.0.2    |Net0  |VPC0  |[172.2,...]
|====================


== Highlevel Components

=== Communication Manager

This will interface with Kafka or gRPC (for controller fast path) to process goal state updates from Alcor Controllers. It will subscribe to topics published by Alcor VPC Controller in Kafka. ACA can also publish (health/error) information back to Alcor Controllers through gRPC.

=== Network Configurator

1. In order to help Network Controller to determine the host machine network setup. It will collect the network configuration from the host machine and send to Network Controller through Kafka, including:
. SRIOV support
. DPDK support
. Bandwidth (10G/25G/40G)
. IP of the host machine (is it DHCP or assigned?)
2. Network Controller will decide what network configuration to be applied on the host machine, and send it to ACA through Kafka.
3. Connect vNICs to the vPorts once the VM/Container is running.

=== Security policy Manager

Responsible to configure and update the security policies on vNICs/vPorts.

=== Transit Agent Manager

This will interface with user mode Transit daemon to program the transit router/switch/endpoint. Using the below APIs:

*Transit/src/rpcgen/trn_rpc_protocol.x*

[source,c]
------------------------------------------------------------
int UPDATE_VPC(rpc_trn_vpc_t) = 1;
int UPDATE_NET(rpc_trn_network_t) = 2;
int UPDATE_EP(rpc_trn_endpoint_t) = 3;
int UPDATE_AGENT_EP(rpc_trn_endpoint_t) = 4;
int UPDATE_AGENT_MD(rpc_trn_agent_metadata_t) = 5;

int DELETE_VPC(rpc_trn_vpc_key_t) = 6;
int DELETE_NET(rpc_trn_network_key_t) = 7;
int DELETE_EP(rpc_trn_endpoint_key_t) = 8;
int DELETE_AGENT_EP(rpc_trn_endpoint_key_t) = 9;
int DELETE_AGENT_MD(void) = 10;

rpc_trn_vpc_t      GET_VPC(rpc_trn_vpc_key_t) = 11;
rpc_trn_network_t  GET_NET(rpc_trn_network_key_t) = 12;
rpc_trn_endpoint_t GET_EP(rpc_trn_endpoint_key_t) = 13;
rpc_trn_endpoint_t GET_AGENT_EP(rpc_trn_endpoint_key_t) = 14;
rpc_trn_agent_metadata_t GET_AGENT_MD(void) = 15;

int LOAD_TRANSIT_XDP(rpc_trn_xdp_intf_t) = 16;
int LOAD_TRANSIT_AGENT_XDP(rpc_trn_xdp_intf_t) = 17;

int UNLOAD_TRANSIT_XDP(rpc_intf_t) = 18;
int UNLOAD_TRANSIT_AGENT_XDP(rpc_intf_t) = 19;
------------------------------------------------------------

Note: XDP programs are preloaded on physical NIC during system bring up. With new VMs/Containers, Virtual interface for new VMs/Containers will have XDP program loaded by ACA during their creation tracked by issue #50.

=== Log Manager

It will create the log file, manage the log configuration and maintain the ACA logs. Need to decide on how many days to keep the logs, e.g. 7 days.

The log should at least contain a timestamp, source file name and line number, message. The ACA code should be able to specify the log level and can configure the targetted log level at runtime.
Syslog is a good target framework, it is a proven mechanism in linux and it is https://askubuntu.com/questions/184949/how-do-i-limit-the-size-of-my-syslog[configurable for our needs]. See reference session for more information.


== Interface with Alcor VPC Controller
. Goal State object: +
Alcor VPC Controller sends down goal state object to ACA in the format of protobuf 3 messages to support cross language and cross machine model. The goal state object contains 0 to n vpc_states/subnet_states/port_state/security_group_states configurations. When ACA receives the goal state object, it will loop through each configuration to determine the intent update by looking at the OperationType. ACA will then parse the configuration and execute the needed change on the host machine, including XDP programming using transit daemon. Below is the highlevel GoalState definition:

*AliothController/src/schema/proto3/goalstate.proto*

[source,java]
------------------------------------------------------------
syntax = "proto3";

package aliothcontroller;

option java_package = "com.futurewei.alioth.controller.schema";

import "vpc.proto";
import "subnet.proto";
import "port.proto";
import "securitygroup.proto";

message GoalState {
   repeated VpcState vpc_states = 1;
   repeated SubnetState subnet_states = 2;
   repeated PortState port_states = 3;
   repeated SecurityGroupState security_group_states = 4;
}
------------------------------------------------------------

. Kafka messaging path: +
In order to have a scalable, high performance and highly reliable communication channel between Alcor VPC Controller and 100s of thousands of compute hosts, Kafka was used because of its features and proven performance. For most of host network configurations, Alcor VPC Controller will publish the goal state object as a Kafka message in proto3 format into a Kafka topic specific to a compute/transit host. The ACA running on the targetted host will consume that message and apply network configuration accordingly.

. gRPC fast path: +
We need an ultra low latency Alcor control path to support customer scenarios like serverless where it has very low latency budget (<100ms) for end to end. An async gRPC server was added into ACA in conjunction with the Kakfa cosumer to process goal state updates faster. See the "Thread modeling" session below for more information the threading implementation.

. Security Group API: +
https://github.com/openstack/neutron/blob/master/neutron/agent/securitygroups_rpc.py

. Authentication and Authorization: +
Openstack documentation on using authentication token: +
https://docs.openstack.org/ocata/config-reference/common-configurations/auth.html

== Thread modeling
There will be one thread for Kafka consumer to receive Alcor VPC controller goal state update. Another thread should be used to post the respond on the goal state update result to Kakfa so that the controller can process it.

There will be another thread for async gRPC server to handle goal state update request for control fast path (currently targetting serverless scenario for fast provisioning). The gRPC async library will handle the client call from Alcor VPC controller, put the work item into its own completion queue, and reponds to the client call quickly. It will transparently create new threads to process the work items in its completion queue. Once a work item is completed, it will create a gRPC response to the original client call with the goal state update result.


== Interface with Alkaid
TBD, Alkaid is our new Cloud Fabric Compute infrastructure...


== API Versioning of Alcor Control Agent and Alcor VPC Controller

==== Motivation
When making major changes to code, the components need to be versioned in such a way so that old clients have time to upgrade, and new clients can use the new features without issues.

==== Strategy
The strategy is to have the two components, agent and controller, explicitly state the API version in their messages.
Thus, every message/call between the Controller and the ACA will have an API version tagged. +

The components will support a range of different API versions by defining the max API version and min API version supported. +
These fields will then be incremented respectively as features are +
upgraded, and deprecated.

For major version upgrades, the strategy will be to

. Deploy changes to all ACA first
. Deploy changes to Network Controller once all Agents have been upgraded

==== Example
For example, say there is a new update to support SR-IOV.

[width="100%",options="header"]
|====================
|Case|Controller Action|Agent Action
|V1 Agent and V2 Controller|Controller sends a new V2 config to enable SR-IOV.|Agent sees unknown version in message and fails
|V2 Agent and V1 Controller|Controller sends a V1 Config|Agent sees V1 version in message and executes V1 calls
|====================

== Testing strategy
TBD, We are planning to use CMocka for unit/functional testing and gcov+lcov for code coverage analysis.

== Reference

. https://docs.openstack.org/neutron/pike/contributor/internals/openvswitch_agent.html
. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md
. https://dzone.com/articles/backward-compatibility-check-for-rest-apis
. https://stackoverflow.com/questions/29871744/how-do-you-manage-the-underlying-codebase-for-a-versioned-api
. https://github.com/futurewei-cloud/Transit/blob/master/docs/modules/ROOT/pages/design/monitoring.adoc[Alcor Control Agent and SN Agent will work independently]
. https://stackoverflow.com/questions/158457/daemon-logging-in-linux[Logging in Linux]
. https://support.huaweicloud.com/en-us/usermanual-ecs/en-us_topic_0030878383.html[Security Group Rule format in Huawei Cloud]

[width="100%",options="header"]
|====================
| Parameter | Description | Example Value
| Protocol | Specifies the network protocol for which the security group rule takes effect. The value can be **TCP**, **UDP**, **ICMP**, **HTTP**, or others.
 | TCP
| Port | Specifies the port or port range for which the security group rule takes effect. The value ranges from **0** to **65535**. | 22 or 22-30
| Source | Specifies the source for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Inbound**. The value can be an IP address or a security group.
 | 0.0.0.0/0
default
| Destination | Specifies the destination for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Outbound**. The value can be an IP address or a security group. | 0.0.0.0/0
default
|====================
