= Cloud Fabric Network Control Agent

== Summary

The Cloud Fabric Network Control Agent runs on each host machine. It serves as a simple stateless proxy between network controller and host machine networking components for control plane operations.


== Requirements

. Network Control Agent will reside on each host machine to interface between network controller and host networking components. The main responsibility is to create and configure network to
enable connectivity (VPC IP < - > Physical IP mapping) between VMs/Containers within the datacenter and the outside world through EIP.

. It will update networking configuration on the host:
	.. Create vPort for VM/Container (unless this is done by Compute agent)
	.. Configure vNIC and vPort, connect them for the VM/Container
	.. Attach Security group to a vNIC TODO: add more detail after dataplane performance analysis without it
	.. Attached transit agent to the corresponding vNIC(veth) and transit switch/router on the physical NIC

. It will also update VPC Configuration (VPC, Subnet, Security Group, Routing) including CRUD (Create/Read/Update/Delete) VPC/Subnet/Endpoint.

== Roles

The network control agent will have the following roles, the code will live in one binary.

. Local Host Networking configuration
. Network Control Agent Health management, transit daemon and agents health, VM/Container networking health monitoring
.. TODO: need to expand this, will likely live in a seperate doc, post 9/30
. Transit (dataplane) user mode programming proxy
. Network Component upgrade manager

== Communication between Network Control Agent and kernel mode Transit Agent

                    +--------------------+
                    |  Network Control   |
                    |     Agent          |
                    +--------------------+
                    |  Transit Daemon    |
                    +------------------ -+   User Mode
         +--------------------------------------------------+
                    +--------------------+   Kernel Mode
                    |  Transit Agent     |
                    |     xdp program    |
                    +--------------------+

== Workflow

. Customer creates a new VPC
	.. Allocate transit router
		... Smart placement [router1, router2]
		... Go to router1, router2 and add VPC to the VPC table (Call “Update VPC”) (VPC table)
. Customer creates new network(subnet)
	.. Allocate transit switch
		... Smart placement [Switch1, Switch2]
		... Go to router1, and router2 and “Update net” (net table)
		... Go to s1, s2 and call “Update net" (net table)
. Customer create a VM with endpoint 1 at net0
	.. Allocate endpoint
		... Go to all switches (s1,s2) update endpoint
			.... make sure at least one or more transit switch ready before the next step
			.... TODO: need to be able to notify network controller that a particular transit switch programming is completed
		... Go to VM Host create endpoint and update the transit switch info in endpoint table

== Network Configuration

[width="100%",options="header"]
|====================
| VPC table  |
| VPC0 | {10.0.0.0/16,[172.3,172.4]}
|====================

[width="100%",options="header"]
|====================
|Network Table   |
|Net0   |{10.0.0.0/25,[172.1,172.2]}
|====================

[width="100%",options="header"]
|====================
|Endpoint Table   |  |  |
|10.0.0.1  |Net0  |VPC0  |[172.1,...]
|10.0.0.2    |Net0  |VPC0  |[172.2,...]
|====================


== Highlevel Components

=== Communication Manager

This will interface with Kafka to process messages from Network Controller. It will subscribe to topics published by Network Controller. Network Control Agent can also publish (health/error) information to Network Controller through Kafka.

=== Network Configurator

1. In order to help Network Controller to determine the host machine network setup. It will collect the network configuration from the host machine and send to Network Controller through Kafka, including:
. SRIOV support
. DPDK support
. Bandwidth (10G/25G/40G)
. IP of the host machine (is it DHCP or assigned?)
2. Network Controller will decide what network configuration to be applied on the host machine, and send it to network control agent through Kafka.
3. Connect vNICs to the vPorts once the VM/Container is running.

=== Security policy Manager

Responsible to configure and update the security policies on vNICs/vPorts.

=== Transit Agent Manager

This will interface with user mode Transit daemon to program the transit router/switch/endpoint. Using the below APIs:

                int UPDATE_VPC(rpc_trn_vpc_t) = 1;
                int UPDATE_NET(rpc_trn_network_t) = 2;
                int UPDATE_EP(rpc_trn_endpoint_t) = 3;

                int DELETE_VPC(rpc_trn_vpc_key_t) = 4;
                int DELETE_NET(rpc_trn_network_key_t) = 5;
                int DELETE_EP(rpc_trn_endpoint_key_t) = 6;

                rpc_trn_vpc_t      GET_VPC(rpc_trn_vpc_key_t) = 7;
                rpc_trn_network_t  GET_NET(rpc_trn_network_key_t) = 8;
                rpc_trn_endpoint_t GET_EP(rpc_trn_endpoint_key_t) = 9;

                int LOAD_TRANSIT_XDP(rpc_trn_xdp_intf) = 11;
                int LOAD_TRANSIT_AGENT_XDP(rpc_trn_xdp_intf) = 12;

Note: XDP programs are preloaded on both physical NIC and vNIC as created by the VM. P0 for 9/30.

=== Log Manager

It will create the log file, manage the log configuration and maintain the Network control agent logs. Need to decide on how many days to keep the logs, e.g. 7 days.

The log should at least contain a timestamp, source file name and line number, message. The network control agent code should be able to specify the log level and can configure the targetted log level at runtime.
Syslog is a good target framework, it is a proven mechanism in linux and it is https://askubuntu.com/questions/184949/how-do-i-limit-the-size-of-my-syslog[configurable for our needs]. See reference session for more information.


== Interface with Network Controller
Working in progress...

. Security Group API: +
https://github.com/openstack/neutron/blob/master/neutron/agent/securitygroups_rpc.py

. Communication Method (Kafka) and message format

. Authentication and Authorization: +
Huawei Cloud allow either using tokens (valid for 24 hours) or AK/SK when calling ECS APIs. +
https://support-intl.huaweicloud.com/en-us/api-ecs/en-us_topic_0124306062.html +
Openstack only talks about using authentication token: +
https://docs.openstack.org/ocata/config-reference/common-configurations/auth.html


== API Versioning of Network Control Agent and Network Controller

==== Motivation
When making major changes to code, the components need to be versioned in such a way so that old clients have time to upgrade, and new clients can use the new features without issues.

==== Strategy
The strategy is to have the two components, agent and controller, explicitly state the API version in their messages.
Thus, very message/call between the Controller and the Network Control Agent will have an API version tagged. +

The components will support a range of different API versions by defining the max API version and min API version supported. +
These fields will then be incremented respectively as features are +
upgraded, and deprecated.

For major version upgrades, the strategy will be to

. Deploy changes to all Network Control Agents first
. Deploy changes to Network Controller once all Agents have been upgraded

==== Example
For example, say there is a new update to support SR-IOV.

[width="100%",options="header"]
|====================
|Case|Controller Action|Agent Action
|V1 Agent and V2 Controller|Controller sends a new V2 config to enable SR-IOV.|Agent sees unknown version in message and fails
|V2 Agent and V1 Controller|Controller sends a V1 Config|Agent sees V1 version in message and executes V1 calls
|====================

== TODO
. need to define the milestones for 7/30, 8/30 and 9/30
. need to define the responsiblity and boundry for different networking agent and maybe compute agent

== Reference

. https://docs.openstack.org/neutron/pike/contributor/internals/openvswitch_agent.html
. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md
. https://dzone.com/articles/backward-compatibility-check-for-rest-apis
. https://stackoverflow.com/questions/29871744/how-do-you-manage-the-underlying-codebase-for-a-versioned-api
. https://github.com/futurewei-cloud/Transit/blob/master/docs/modules/ROOT/pages/design/monitoring.adoc[Network Control Agent and SN Agent will work independently]
. https://stackoverflow.com/questions/158457/daemon-logging-in-linux[Logging in Linux]
. https://support.huaweicloud.com/en-us/usermanual-ecs/en-us_topic_0030878383.html[Security Group Rule format in Huawei Cloud]

[width="100%",options="header"]
|====================
| Parameter | Description | Example Value
| Protocol | Specifies the network protocol for which the security group rule takes effect. The value can be **TCP**, **UDP**, **ICMP**, **HTTP**, or others.
 | TCP
| Port | Specifies the port or port range for which the security group rule takes effect. The value ranges from **0** to **65535**. | 22 or 22-30
| Source | Specifies the source for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Inbound**. The value can be an IP address or a security group.
 | 0.0.0.0/0
default
| Destination | Specifies the destination for which the security group rule takes effect. This parameter is required when **Transfer Direction** is set to **Outbound**. The value can be an IP address or a security group. | 0.0.0.0/0
default
|====================
