= OVS Programming Design
Eric Li <sze.li@futurewei.com>, Xiaodong Zhang <xzhang2@futurewei.com>
v0.1, 2020-04-07
:toc: right


== Architecture Overview

The Alcor Control Agent (ACA) running on the compute host provides the support of OVS dataplane programming through its dataplane abstraction layer interface. During startup time, ACA will be configured to which dataplace to use (OVS - default or Mizar), and then execute the corresponding code through the dataplane abstraction layer.

Unlike openstack neutron which uses at least 5 RPC messages to simply configure a new port and have chatty model between neutron server and neutron agents. Alcor design have only one message send from Alcor Controller to ACA, and that message would contain all the necessary network/port/security group/DHCP configuration to complete the configuration on compute/network host machine. 

The message can contain one or more (batching) configuration (e.g. 1000s new ports). ACA will parse the message in the Network State Handler module and then send the work item(s) to different ACA components for processing. It has with ability to execute multiple work items in parallel by default to greatly reduce the configuration time. Our previous data showed that parallel process would provide 7 times gain compare do serial processing 100s of configurations. Once all the work items are completed, ACA will provide the one response message back to Alcor controller on success/fail status and also elapse time stamps for record tracking. To summerize, we are looking at just one message send to ACA and one reply back to Alcor control to configure one to 1000s of new ports.


=== Agent APIs for Core Network Programming

Here is the proposed implementation for Core Network programming interface:

[source,c++]
------------------------------------------------------------
// Core Network Programming Interface class
class Core_Network_Programming_Interface {
   public:
      // pure virtual functions providing interface framework.
      virtual int initialize() = 0;

      virtual int update_vpc_state_workitem(const VpcState current_VpcState,
                                            GoalStateOperationReply &gsOperationReply) = 0;

      virtual int update_subnet_state_workitem(const SubnetState current_SubnetState,
                                               GoalStateOperationReply &gsOperationReply) = 0;

      virtual int update_port_state_workitem(const PortState current_PortState,
                                             const alcorcontroller::GoalState &parsed_struct,
                                             GoalStateOperationReply &gsOperationReply) = 0;
};
------------------------------------------------------------


=== Communication with OVS

TBD: XiaoDong to update the picture below, it will be good to add some text here also

                    +--------------------+
                    |  Alcor Control     |
                    |     Agent          |
                    +--------------------+
                    |  ovs-vsctl and     |
                    |   ofctl_api?       |
                    +--------------------+
         +--------------------------------------------------+
                    +--------------------+
                    |  ovs-db?           |
                    +--------------------+


=== Communication Protocol

TBD - XiaoDong


== Workflow of Network Configuration Programming

. ovs-vsctl
. idl binding like this http://docs.openvswitch.org/en/latest/topics/idl-compound-indexes/
. ofctl.api.send_msg (packet) (OSKen)

TBD - XiaoDong, we want to get to the next level of detail. Imagine we are going to start writing the code next week, let's give an example of the calls to make to configuration a port for vxlan. We want to understand the options/parameters needed so that we can check to make the network state message from Alcor Controller contains that information.


=== Basic Port Programming

TBD - Eric

=== Router Programming

TBD

=== Security Group Programming

TBD

=== Network ACL Programming

TBD

== Implementation Details

TBD - XiaoDong/Eric

Initialization - ACA will initialize OVS during its startup time. We will likely start OVS service directly. <<start-ovs>>

Another option is to initialize OVS through command line:

[source,c++]
------------------------------------------------------------
a. start ovsdb-server: ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock  \
  --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
  --private-key=db:Open_vSwitch,SSL,private_key  \
  --certificate=db:Open_vSwitch,SSL,certificate     \
  --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert  \
  --log-file=/var/log/openvswitch/ovs-vswitchd.log \
  -vsyslog:dbg -vfile:dbg  --pidfile --detach

b. start vswitchd: ovs-vswitchd -v --pidfile --detach \
 --log-file=/var/log/openvswitch/ovs-vswitchd.log \
 -vconsole:err -vsyslog:info -vfile:info

c. use cmd to init: ovs-vsctl --no-wait init
------------------------------------------------------------

ACA will create the required br-int, br-tun bridges during agent init time, and recreated later during core network programming if needed.

.. what is the exact command to connect the new port to the new br-tun, and enable encap/decap?
... A: ovs-vsctl add-port set interface type=vxlan is the one which would do encap/decap

== Comparison with Neutron OVS Agent

TBD - XiaoDong/Eric

 How is the perf, latency and availablity etc compare to Neutron?

. need to measure the perf for large VPC - 64,000 EP?
. need to measure the perf for a lot of VPCs
. How are the OVS bridge performance when it is at scale? Is that the reason why it use multiple bridges (br-int, br-tun, br-ex)?


== Background of OVS Dataplane

"Open vSwitch is a production quality, multilayer virtual switch licensed under the open source Apache 2.0 license.  It is designed to enable massive network automation through programmatic extension, while still supporting standard management interfaces and protocols."<<ovs>>

We decided to support OVS dataplace not only because it is the main dataplane for OpenStack, it is also because its extensive features support as a software network switch implementation meeting our Alcor Cloud Native SDN requirements.

TBD - Eric to add more info


=== OVS Interfaces

TBD - Xiaodong


=== OVS Major Components

TBD - Eric

Need a good diagram here.


== Pending Items

. TBD - Eric: How do Alcor controller tell us which OVS port to configure (using device ID)? The information is already passed by Nova to Neutron today, we just need to figure out the port ID format and confirm we can use it.

. what happen when there are multiple physical NICs on the system, which NIC do we pick to hook up to br-ex (if needed)?

. what happen if host crashed, do we save the OVS config locally and restore it? Or we ask the Alcor controller for the whole set of cofiguration upon restart?


[bibliography]
== References

- [[[ovs,1]]] https://www.openvswitch.org/
- [[[start-ovs,2]]] https://github.com/openstack/neutron/blob/c2d18cda6f3716965f0843da213985b4b7c6bb41/devstack/lib/ovs#L153
- [[[cidl,3]]] http://docs.openvswitch.org/en/latest/topics/idl-compound-indexes/