name: Agent Build CI

on:
  push:
    paths:
      - '!docs/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Alcor Control Agent
        run: ./build/build.sh
        working-directory: .