name: Agent Build CI

on:
  push:
    paths:
      - '**'
      - '!docs/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build Alcor Control Agent
        run: ./build/build.sh
        working-directory: .
