name: Agent Build CI

on:
  push:
    paths:
      - '**'
      - '!docs/**'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Build Alcor Control Agent
        run: ./build/build.sh
        working-directory: .
