name: Agent Build CI

on:
  push:
    paths:
      - '**'
      - '!docs/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Build Alcor Control Agent
        run: ./build/build.sh
        working-directory: .
